#!/bin/bash

sudo pacman -Syu
sudo pacman -S --needed git base-devel
sudo chown $USER /opt
cd /opt/
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --needed --noconfirm
yay --save --answerclean None --answerdiff None

sudo usermod --shell /bin/zsh $USER
yay -S -noconfirm --needed python-pip kitty mdcat nerd-fonts-fira-code nvim-packer-git lua-language-server-git

# Config installation
git clone --bare git@github.com:tobyto-cs/dotfiles.git $HOME/.cfg
/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout
