local utils = require('base16-nvim.utils')
local hi = utils.hi
local cond = utils.cond
local M = {}

function M.setup()
  hi("Normal",        "b5", "b0")
  hi("Bold",          nil, "b", { "bold" })
  hi("Debug",         "b8", nil)
  hi("Directory",     "bD", nil)
  hi("Error",         "b0", "b8")
  hi("ErrorMsg",      "b8", "b0")
  hi("Exception",     "b8", nil)
  hi("FoldColumn",    "bC", "b1")
  hi("Folded",        "b3", "b1")
  hi("IncSearch",     "b1", "b9")
  hi("Italic",        nil, "b", { "italic" })
  hi("Macro",         "b8", nil)
  hi("MatchParen",    nil, "b3")
  hi("ModeMsg",       "bB", nil)
  hi("MoreMsg",       "bB", nil)
  hi("Question",      "bD", nil)
  hi("Search",        "b1", "bA")
  hi("Substitute",    "b1", "bA")
  hi("SpecialKey",    "b3", nil)
  hi("TooLong",       "b8", nil)
  hi("Underlined",    "b8", nil)
  hi("Visual",        nil, "b2")
  hi("VisualNOS",     "b8", nil)
  hi("WarningMsg",    "b8", nil)
  hi("WildMenu",      "b8", nil)
  hi("Title",         "bD", nil)
  hi("Conceal",       "bD", "b0")
  hi("Cursor",        "b0", "b5")
  hi("NonText",       "b3", nil)
  hi("LineNr",        "b5", "b0")
  hi("SignColumn",    "b5", "b1")
  hi("StatusLine",    "b4", "b0")
  hi("StatusLineNC",  "b3", "b1")
  hi("VertSplit",     "b1", "b0")
  hi("ColorColumn",   nil, "b1")
  hi("CursorColumn",  nil, "b1")
  hi("CursorLine",    nil, "b1")
  hi("CursorLineNr",  "b4", "b1")
  hi("QuickFixLine",  nil, "b1")
  hi("PMenu",         "b5", "b1")
  hi("PMenuSel",      "b1", "b5")
  hi("TabLine",       "b3", "b1")
  hi("TabLineFill",   "b3", "b1")
  hi("TabLineSel",    "bB", "b1")

  -- Standard syntax highlighting
  hi("Boolean",      "b9", nil)
  hi("Character",    "b8", nil)
  hi("Comment",      "b3", nil, { "italic" })
  hi("Conditional",  "bE", nil)
  hi("Constant",     "b9", nil)
  hi("Define",       "bE", nil)
  hi("Delimiter",    "bF", nil)
  hi("Float",        "b9", nil)
  hi("Function",     "bD", nil, { "italic" })
  hi("Identifier",   "b8", nil)
  hi("Include",      "bD", nil, { "bold" })
  hi("Keyword",      "bE", nil, { "bold" })
  hi("LspCxxHlGroupNamespace", "bE", nil)
  hi("Label",        "bA", nil)
  hi("Number",       "b9", nil)
  hi("Operator",     "b5", nil)
  hi("PreProc",      "bA", nil)
  hi("Repeat",       "bA", nil)
  hi("Special",      "bC", nil)
  hi("SpecialChar",  "bF", nil)
  hi("Statement",    "b8", nil)
  hi("StorageClass", "bA", nil)
  hi("String",       "bB", nil)
  hi("Structure",    "bE", nil)
  hi("Tag",          "bA", nil)
  hi("Todo",         "bA", "b1")
  hi("Type",         "bA", nil)
  hi("Typedef",      "bA", nil)

  -- Spelling highlighting
  hi("SpellBad",     nil, "b", { "undercurl" }, "b8")
  hi("SpellLocal",   nil, "b", { "undercurl" }, "bC")
  hi("SpellCap",     nil, "b", { "undercurl" }, "bD")
  hi("SpellRare",    nil, "b", { "undercurl" }, "bE")

  -- Floating windows
  hi("NormalFloat", "b5", "b1")
end

return M
