#!/bin/bash

color3=$HOME/.themes/FlatColor/colors3
rm $color3
touch $color3
while IFS= read -r line; do
  if [[ "$line" != \#* ]]; then
    printf "$line\n" | tee -a $color3 > /dev/null
  fi
done < $HOME/.themes/FlatColor/colors3tmp
xsettingsd &> /dev/null &
sleep 0.1
pid=$!
disown
kill $pid
